# Generated by Django 6.0.5 on 2026-05-29 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['name'], 'verbose_name': 'Exercise', 'verbose_name_plural': 'Exercises'},
        ),
        migrations.AlterModelOptions(
            name='musclegroup',
            options={'ordering': ['name'], 'verbose_name': 'Muscle Group', 'verbose_name_plural': 'Muscle Groups'},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exercises/images/'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercises.musclegroup'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='musclegroup',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['name'], name='exercises_e_name_9bce89_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['muscle_group'], name='exercises_e_muscle__a611c7_idx'),
        ),
        migrations.AddIndex(
            model_name='musclegroup',
            index=models.Index(fields=['name'], name='exercises_m_name_5500e7_idx'),
        ),
    ]
