FROM python:3.12-slim

WORKDIR /app

COPY backend/ .

RUN pip install --no-cache-dir -r AndryxaGym_backend/requirements.txt

CMD ["python", "AndryxaGym_backend/manage.py", "runserver", "0.0.0.0:8000"]